config/routes.rb
Rails.application.routes.draw do

  resources :account_activations, only: [:edit]

  resources :users do
    resources :feeds
  end

  get 'about' => 'static_pages#about'
  get 'opensource' => 'static_pages#opensource'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root 'static_pages#home'
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/feeds_users.rb
class FeedsUsers < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :activation_token

  validates :email, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_secure_password

  has_and_belongs_to_many :feeds

  before_create :create_activation_token

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

 private

    def create_activation_token
      self.activation_token  = SecureRandom.urlsafe_base64
      self.activation_digest = create_digest(self.activation_token)
    end

    def create_digest(token)
      BCrypt::Password.create(token, cost: cost)
    end

    def cost
      if ActiveModel::SecurePassword.min_cost
        return BCrypt::Engine::MIN_COST
      else
        return BCrypt::Engine.cost
      end
    end



end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      user.update_attribute(:activated, true)
      user.update_attribute(:activated_at, Time.zone.now)
      log_in user
      flash[:success] = "Account activated!"
      redirect_to user
    else
      flash[:danger] = "Invalid activation link"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please log in.'
      redirect_to login_url
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_action :logged_in_user

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = @user.feeds.paginate(:page => params[:page],
                                  :per_page => 10)
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    feed = @user.feeds.new(feed_params)

    respond_to do |format|
      if feed.valid?
        @user_feed = @user.feeds.create(feed_params)
        format.html { redirect_to user_feed_path(id: @user_feed.id),
                      notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to user_feed_path(id: @feed), notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to user_feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:url, :name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in(user)
        redirect_to(user)
      else
        message  = "Account not activated. Check your email for the activation link."
        flash[:warning] = message
        redirect_to login_url
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def opensource
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save && UserMailer.account_activation(@user).deliver_now
      flash[:info] = "Please check your email to activate your account"
      redirect_to login_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:first_name,
                                   :last_name,
                                   :email,
                                   :password,
                                   :password_confirmation)
    end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  def logged_in?
    !current_user.nil?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/account_activations/edit.html.erb
<h1>AccountActivations#edit</h1>
<p>Find me in app/views/account_activations/edit.html.erb</p>

app/views/feeds/_form.html.erb
<%= form_for([@user,@feed]) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', user_feed_path %> |
<%= link_to 'Back', user_feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Feeds</h1>

<p>
<%= link_to 'New Feed', new_user_feed_path %>
</p>



<div id="feeds"></div>


<img src='http://www.fostersystems.com/ccdata/images/spinner.gif' id='next_page_spinner' />

<script>
  var userId = <%= @user.id %>;
</script>
<%= javascript_include_tag 'pagination' %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', user_feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @feed.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<%= link_to 'Edit', edit_user_feed_path(id: @feed) %> |
<%= link_to 'Back', user_feeds_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="navbar-header">

    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
    </button> <a class="navbar-brand" href="#">Brand</a>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="active">
        <%= link_to 'Home', root_path %>
      </li>
      <li>
        <%= link_to 'About', about_path %>
      </li>
      <li>
        <%= link_to 'Opensource at WolfieReader', opensource_path %>
      </li>
      <% if logged_in? %>
        <li>
          <%= link_to 'Dashboard', current_user %>
        </li>
        <li>
          <%= link_to 'Logout', logout_path, method: "delete" %>
        </li>
      <% else %>
        <li>
          <%= link_to 'Login', login_path %>
        </li>
        <li>
          <%= link_to 'Register', new_user_path %>
        </li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WolfieReader</title>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.0/handlebars.min.js"> </script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navigation' %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
  <h1>Welcome to WolfieReader</h1>
  <p>Since they shut down Google Reader we're going to bring it back like the party never left and with more features. Well, maybe.</p>


  <p><%= link_to 'About', about_path, class: "btn btn-primary btn-lg" %></p>
</div>

app/views/static_pages/opensource.html.erb
<%
    gems = [{name: 'rails', version: '4.2.2'},
            {name: 'bootstrap-sass', version: '3.2.0.0'},
            {name: 'sass-rails', version: '5.0.2'},
            {name: 'uglifier', version: '2.5.3'},
            {name: 'coffee-rails', version: '4.1.0'},
            {name: 'jquery-rails', version: '4.0.3'},
            {name: 'turbolinks', version: '2.3.0'},
            {name: 'jbuilder', version: '2.2.3'},
            {name: 'sdoc', version: '0.4.0' },
            {name: 'sqlite3', version: '1.3.9'},
            {name: 'byebug', version: '3.4.0'},
            {name: 'web-console', version: '2.0.0.beta3'},
            {name: 'spring', version: '1.1.3'},
            {name: 'minitest-reporters', version: '1.0.5'},
            {name: 'mini_backtrace', version: '0.1.3'},
            {name: 'guard-minitest', version: '2.3.1'},
            {name: 'pg', version: '0.17.1'},
            {name: 'rails_12factor', version: '0.0.2'}]
%>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>Name</th>
      <th>Version</th>
    </tr>
  </thead>
  <tbody>
    <% gems.each do |gem| %>
      <tr>
        <td><%= gem[:name] %></td>
        <td><%= gem[:version] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <%= form_for(@user, html: {class: "form-horizontal"}) do |f| %>
      <fieldset>

        <div class="form-group">
          <%= f.label :first_name, class: 'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.text_field :first_name, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :last_name, class: 'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.text_field :last_name, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :email, class: 'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.email_field :email, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :password, class: 'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.password_field :password, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation, "Confirmation", class: 'col-lg-2 control-label' %>
          <div class="col-lg-10">
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-lg-12">
            <%= f.submit "Create my account", class: "btn btn-primary" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>Account</h1>

<ul>
  <li><%= link_to 'My Feeds', user_feeds_path(user_id: @user) %></li>
  <li><a href="#">Change Password</a></li>
</ul>